### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by 06Liz** [GuangYuanKK/DiffMSR#4]
Name MCSRPairedDataset is not found, use name: MCSRPairedDataset_basicsr!
Traceback (most recent call last):
  File "DiffMSR_Main/train.py", line 20, in <module>
    train_pipeline(root_path)
  File "/root/autodl-tmp/DiffMSR-main/DiffMSR_Main/train_pipeline.py", line 121, in train_pipeline
    result = create_train_val_dataloader(opt, logger)
  File "/root/autodl-tmp/DiffMSR-main/DiffMSR_Main/train_pipeline.py", line 36, in create_train_val_dataloader
    train_set = build_dataset(dataset_opt)
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/data/__init__.py", line 34, in build_dataset
    dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt)
  File "/root/miniconda3/lib/python3.8/site-packages/basicsr/utils/registry.py", line 71, in get
    raise KeyError(f"No object named '{name}' found in '{self._name}' registry!")
KeyError: "No object named 'MCSRPairedDataset' found in 'dataset' registry!"
请问这个问题怎么解决

**Comment by cqutYang** [comment]
> 找不到名称 MCSRPairedDataset，请使用名称：MCSRPairedDataset_basicsr！回溯（最近一次调用）：文件“DiffMSR_Main/train.py”，第 20 行，train_pipeline（root_path） 文件“/root/autodl-tmp/DiffMSR-main/DiffMSR_Main/train_pipeline.py”，第 121 行，train_pipeline结果 = create_train_val_dataloader（opt，记录器） 文件“/root/autodl-tmp/DiffMSR-main/DiffMSR_Main/train_pipeline.py”，第 36 行，create_train_val_dataloader train_set = build_dataset（dataset_opt）文件“/root/miniconda3/lib/python3.8/site-packages/basicsr/data/**init**.py”，第 34 行，在数据集build_dataset = DATASET_REGISTRY.get（dataset_opt['type']）（dataset_opt） 文件“/root/miniconda3/lib/python3.8/site-packages/basicsr/utils/registry.py”，第 71 行，在 get raise KeyError（f“在 '{self._name}' 注册表中找不到名为 '{name}' 的对象！”） KeyError：“在'dataset'注册表中找不到名为'MCSRPairedDataset'的对象！ 请问这个问题怎么解决

请问，你这个问题解决了吗

**Comment by cqutYang** [comment]
> Name MCSRPairedDataset is not found, use name: MCSRPairedDataset_basicsr! Traceback (most recent call last): File "DiffMSR_Main/train.py", line 20, in train_pipeline(root_path) File "/root/autodl-tmp/DiffMSR-main/DiffMSR_Main/train_pipeline.py", line 121, in train_pipeline result = create_train_val_dataloader(opt, logger) File "/root/autodl-tmp/DiffMSR-main/DiffMSR_Main/train_pipeline.py", line 36, in create_train_val_dataloader train_set = build_dataset(dataset_opt) File "/root/miniconda3/lib/python3.8/site-packages/basicsr/data/**init**.py", line 34, in build_dataset dataset = DATASET_REGISTRY.get(dataset_opt['type'])(dataset_opt) File "/root/miniconda3/lib/python3.8/site-packages/basicsr/utils/registry.py", line 71, in get raise KeyError(f"No object named '{name}' found in '{self._name}' registry!") KeyError: "No object named 'MCSRPairedDataset' found in 'dataset' registry!" 请问这个问题怎么解决

请问你这个问题解决了吗，怎么解决
