### ISSUE TITLE
data

### ISSUE THREAD

**Issue by TFengXu** [GuangYuanKK/DiffMSR#9]
你好，我在代码里看到你使用了matlab处理了原始MRI数据集，请问能提供下您处理之后的mat数据集吗

**Comment by xuxuduoduomeiGithub** [comment]
> 你好，我在代码里看到你使用了matlab处理了原始MRI数据集，请问能提供下您处理之后的mat数据集吗

你好，你跑通了这个模型吗？我用作者提供的部分mat数据集跑不通

**Comment by TFengXu** [comment]
好像是可以的

**Comment by xuxuduoduomeiGithub** [comment]
> 好像是可以的

请问你是修改了一些配置的吗？我拿项目提供complex_data_demo下的mat数据训练，一直报错：
2024-10-23 12:08:52,558 INFO: Use Exponential Moving Average with decay: 0.999
2024-10-23 12:08:52,598 INFO: Network [DiffMSR_S1] is created.
2024-10-23 12:08:52,688 INFO: Loss [L1Loss] is created.
2024-10-23 12:08:52,690 INFO: Model [DiffMSRS1Model] is created.
2024-10-23 12:08:52,832 INFO: Start training from epoch: 0, iter: 0
Traceback (most recent call last):
  File "DiffMSR_Main/train.py", line 21, in <module>
    train_pipeline(root_path)
  File "f:\diffmsr-main\diffmsr-main\DiffMSR_Main\train_pipeline.py", line 165, in train_pipeline
    model.validation(val_loader, current_iter, tb_logger, opt['val']['save_img'])
  File "D:\anaconda_path\envs\basicsr\lib\site-packages\basicsr\models\base_model.py", line 48, in validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "f:\diffmsr-main\diffmsr-main\DiffMSR_Main\models\DiffMSR_S1_model.py", line 180, in nondist_validation
    super(DiffMSRS1Model, self).nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "D:\anaconda_path\envs\basicsr\lib\site-packages\basicsr\models\sr_model.py", line 160, in nondist_validation
    sr_img = tensor2img([visuals['result']])
  File "D:\anaconda_path\envs\basicsr\lib\site-packages\basicsr\utils\img_util.py", line 84, in tensor2img
    img_np = cv2.cvtColor(img_np, cv2.COLOR_RGB2BGR)
cv2.error: OpenCV(4.9.0) d:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspeci
fied error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,st
ruct cv::impl::A0x59191d0d::Set<3,4,-1>,struct cv::impl::A0x59191d0d::Set<0,2,5>,4>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 2
请问你遇到过吗？怎么解决的，期待回复~

**Comment by TFengXu** [comment]
这个问题好像没遇到过

**Comment by xuxuduoduomeiGithub** [comment]
> 这个问题好像没遇到过

请问你是已经跑通了这个模型已经有结果了嘛？   只是没有作者所使用的数据集？

**Comment by vie131313** [comment]
你们都训练这个模型了吗？效果咋样？
